version: '3.9'
services:
  db:
    image: postgres:15
    container_name: utopiahire-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: utopiahire
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  auth:
    build:
      context: ./auth_fastapi
    container_name: utopiahire-auth-fastapi
    depends_on:
      db:
        condition: service_healthy
    environment:
      - JWT_SECRET=${JWT_SECRET:-change_me_in_prod}
      - REFRESH_SECRET=${REFRESH_SECRET:-another_change_me_secret}
      - ACCESS_EXPIRES_HOURS=${ACCESS_EXPIRES_HOURS:-2}
      - REFRESH_EXPIRES_DAYS=${REFRESH_EXPIRES_DAYS:-7}
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/utopiahire
      - CORS_ORIGINS=http://localhost:5173,http://localhost:5174
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  pgdata:
